version: '3.8'
services:
  canvas-certificate-generator:
    build: .
    container_name: canvas-certificate-generator
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./output:/app/output
    # command: ["dotnet", "CanvasCertificateGenerator.dll"]
    stdin_open: true
    tty: true
